Project page updates
DTS-STN/Service-Canada-Labs pull request #1035
Opened 2024-06-06 13:07 UTC by blai0264

# [Task name](Replace with a link to your task)

Description of the task you completed and/or features added. If it is a visual component or feature,
add a screenshot(s) of it.

## Test Instructions

1. yarn dev
2. go to benefits navigator page
3. examine explore other projects section (check responsiveness)
4. check out component code to see if there is any changes needed
5. yarn storybook
6. check organisms/exploreProjects entry

2024-06-06 14:25 UTC, will0684 requested changes
Nice work, coming along nicely. Just a couple things

2024-06-06 14:40 UTC, blai0264 commented on components/molecules/Card.js
> +          <div className="h:[208px] flex justify-center">
good catch

2024-06-06 14:48 UTC, blai0264 commented on components/molecules/Card.js
> +          <p className="block font-display text-lg lg:px-2 lg:text-md text-custom-blue-projects-link font-bold underline underline-offset-[6px] m-1 py-2 px-6 items-center group-hover:text-custom-blue
gotcha will do

2024-06-07 13:22 UTC, will0684 commented on pages/api/shuffle.js
This is not an API, it is a utility. [An API is something we want other remote/networked applications/devices to access. ](https://aws.amazon.com/what-is/api/). `/lib/utils` is where these things go.

2024-06-07 13:23 UTC, will0684 commented on pages/projects/benefits-navigator/index.js
> +      allProjects: await shuffle(allProjects.sclabsPageV1List.items),
`await` is not necessary here

2024-06-07 14:40 UTC, blai0264 commented on pages/api/shuffle.js
ok noted 👍🏾

2024-06-07 16:55 UTC, will0684 approved these changes
Great work!

2024-06-07 16:56 UTC, merged