[frontend] fix accessibility issues
DTS-STN/Service-Canada-Labs pull request #826
Opened 2023-08-08 18:03 UTC by Fbasham

# [A11y fix](https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities/?workitem=128270)

_Changes_
- remove duplicate ids
- add empty all text for decorate images
- modify headings to increase by 1
- remove tabindex on non-interactive components for keyboard accessibility

2023-08-08 18:12 UTC, andr0272 commented
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1467298438.azurewebsites.net

2023-08-08 18:29 UTC, andr0272 commented
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1467298438.azurewebsites.net

2023-08-09 15:16 UTC, will0684 requested changes
Thank you for this! Just have one change here we'll want to revert relating to the 'default' locale. Kris wrote a decent explanation of why it's being used the way it is [here](https://github.com/DTS-STN/Service-Canada-Labs/pull/577).

2023-08-09 15:16 UTC, will0684 commented on next-i18next.config.js
We use the default locale in the config to support /en/ in the path name. You can read about it here:

https://github.com/DTS-STN/Service-Canada-Labs/pull/577

2023-08-09 17:19 UTC, andr0272 commented
Check out a preview of your pull request here: https://alphasite-appservice-dev-pr-preview-1467298438.azurewebsites.net

2023-08-09 19:25 UTC, will0684 approved these changes
Tested and working well 👍 Nice work thank you!

2023-08-10 10:57 UTC, merged