remove empty p
DTS-STN/Service-Canada-Labs pull request #915
Opened 2023-11-02 12:06 UTC by Fbasham

https://dev.azure.com/VP-BD/DECD/_boards/board/t/Service%20Canada%20Labs/Stories%20and%20Activities?System.WorkItemType=Activity

There was a paragraph tag with empty content adding space.  Removed that tag.

2023-11-02 12:11 UTC, andr0272 commented
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

2023-11-08 13:42 UTC, will0684 requested changes

2023-11-08 13:42 UTC, will0684 commented on pages/projects/dashboard/index.js
> -              <p className="col-span-12 xl:col-span-8">
So from what I understand, we want to try and keep our line length around 65~ characters and no more than 80~. This is why on desktop generally we have our text span 8 out of the 12 columns.

Here's the research from the DS team:

https://www.figma.com/file/XkfHmBPKDcXKkrDVIZFlyF/DS-research-(Copy)?type=whiteboard&node-id=134-10&t=XB93hQUBy11s12gu-4

2023-11-08 14:12 UTC, andr0272 commented
Check out a preview of your pull request here: https://app-servicecanadalabs-dev-pr-preview-1.azurewebsites.net

2023-11-08 15:41 UTC, will0684 approved these changes
Thank you!

2023-11-08 16:01 UTC, merged